In [3]:
a=[1.0,2.0,1.0]
a


[1.0, 2.0, 1.0]

In [5]:
import torch
a=torch.ones(3)
a

tensor([1., 1., 1.])

In [6]:
a[1]

tensor(1.)

In [7]:
float(a[1])

1.0

In [8]:
a[2]=2.0
a

tensor([1., 1., 2.])

In [10]:
points=torch.zeros(6)
points[0]=4.0
points[1]=1.0
points[2]=5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0
points

tensor([4., 1., 5., 3., 2., 1.])

In [11]:
points=torch.tensor([4.0,1.0,5.0,3.0,2.0,1.0])
points

tensor([4., 1., 5., 3., 2., 1.])

In [13]:
float(points[0]),float(points[1])

(4.0, 1.0)

In [14]:
points=torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [15]:
points.shape

torch.Size([3, 2])

In [16]:
points=torch.zeros(3,2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [17]:
points=torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [18]:
points[0,1]

tensor(1.)

In [19]:
points[0]

tensor([4., 1.])

In [23]:
some_list=list(range(6))
some_list[:]
some_list[:]
some_list[1:4]
some_list[1:]
some_list[:4]
some_list[:-1]
some_list[1:4:2]

[1, 3]

In [24]:
points[1:]

tensor([[5., 3.],
        [2., 1.]])

In [26]:
points[1:, :]

tensor([[5., 3.],
        [2., 1.]])

In [27]:
points[None]

tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])

In [28]:
img_t=torch.randn(3,5,5)
weights=torch.tensor([0.2126,0.7152 ,0.0722])


In [29]:
batch_t=torch.randn(2,3,5,5)

In [31]:
img_gray_naive=img_t.mean(-3)
batch_gray_naive=batch_t.mean(-3)
img_gray_naive.shape, batch_gray_naive.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))

In [32]:
unsqueezed_weights=weights.unsqueeze(-1).unsqueeze_(-1)
img_weights=(img_t* unsqueezed_weights)
batch_weights=(batch_t *unsqueezed_weights)
img_gray_weighted=img_weights.sum(-3)
batch_weights.shape, batch_t.shape ,unsqueezed_weights.shape

(torch.Size([2, 3, 5, 5]), torch.Size([2, 3, 5, 5]), torch.Size([3, 1, 1]))

In [33]:
img_gray_weighted_fancy=torch.einsum('...chw,c->...hw',img_t,weights)
batch_gray_weighted_fancy=torch.einsum('...chw,c->...hw',batch_t,weights)
batch_gray_weighted_fancy.shape

torch.Size([2, 5, 5])

In [37]:
weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names=['channels'])
weights_named

tensor([0.2126, 0.7152, 0.0722], names=('channels',))

In [39]:
img_named=img_t.refine_names(...,'channels','rows','columns')
batch_named=batch_t.refine_names(...,'channels','rows','columns')
print("img named :",img_named.shape, img_named.names)
print("batch names:",batch_named.shape, batch_named.names)

img named : torch.Size([3, 5, 5]) ('channels', 'rows', 'columns')
batch names: torch.Size([2, 3, 5, 5]) (None, 'channels', 'rows', 'columns')
