<a href="https://www.kaggle.com/code/afifaf20/03-it-starts-with-a-tensor?scriptVersionId=205323527" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [3]:
a=[1.0,2.0,1.0]
a


[1.0, 2.0, 1.0]

In [5]:
import torch
a=torch.ones(3)
a

tensor([1., 1., 1.])

In [6]:
a[1]

tensor(1.)

In [7]:
float(a[1])

1.0

In [8]:
a[2]=2.0
a

tensor([1., 1., 2.])

In [10]:
points=torch.zeros(6)
points[0]=4.0
points[1]=1.0
points[2]=5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0
points

tensor([4., 1., 5., 3., 2., 1.])

In [11]:
points=torch.tensor([4.0,1.0,5.0,3.0,2.0,1.0])
points

tensor([4., 1., 5., 3., 2., 1.])

In [13]:
float(points[0]),float(points[1])

(4.0, 1.0)

In [14]:
points=torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [15]:
points.shape

torch.Size([3, 2])

In [16]:
points=torch.zeros(3,2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [17]:
points=torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [18]:
points[0,1]

tensor(1.)

In [19]:
points[0]

tensor([4., 1.])

In [23]:
some_list=list(range(6))
some_list[:]
some_list[:]
some_list[1:4]
some_list[1:]
some_list[:4]
some_list[:-1]
some_list[1:4:2]

[1, 3]

In [24]:
points[1:]

tensor([[5., 3.],
        [2., 1.]])

In [26]:
points[1:, :]

tensor([[5., 3.],
        [2., 1.]])

In [27]:
points[None]

tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])

In [28]:
img_t=torch.randn(3,5,5)
weights=torch.tensor([0.2126,0.7152 ,0.0722])


In [29]:
batch_t=torch.randn(2,3,5,5)

In [31]:
img_gray_naive=img_t.mean(-3)
batch_gray_naive=batch_t.mean(-3)
img_gray_naive.shape, batch_gray_naive.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))

In [32]:
unsqueezed_weights=weights.unsqueeze(-1).unsqueeze_(-1)
img_weights=(img_t* unsqueezed_weights)
batch_weights=(batch_t *unsqueezed_weights)
img_gray_weighted=img_weights.sum(-3)
batch_weights.shape, batch_t.shape ,unsqueezed_weights.shape

(torch.Size([2, 3, 5, 5]), torch.Size([2, 3, 5, 5]), torch.Size([3, 1, 1]))

In [33]:
img_gray_weighted_fancy=torch.einsum('...chw,c->...hw',img_t,weights)
batch_gray_weighted_fancy=torch.einsum('...chw,c->...hw',batch_t,weights)
batch_gray_weighted_fancy.shape

torch.Size([2, 5, 5])

In [37]:
weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names=['channels'])
weights_named

tensor([0.2126, 0.7152, 0.0722], names=('channels',))

In [39]:
img_named=img_t.refine_names(...,'channels','rows','columns')
batch_named=batch_t.refine_names(...,'channels','rows','columns')
print("img named :",img_named.shape, img_named.names)
print("batch names:",batch_named.shape, batch_named.names)

img named : torch.Size([3, 5, 5]) ('channels', 'rows', 'columns')
batch names: torch.Size([2, 3, 5, 5]) (None, 'channels', 'rows', 'columns')


In [41]:
weights_aligned=weights_named.align_as(img_named)
weights_aligned.shape, weights_aligned.names

(torch.Size([3, 1, 1]), ('channels', 'rows', 'columns'))

In [43]:
gray_named=(img_named* weights_aligned).sum('channels')
gray_named.shape, gray_named.names

(torch.Size([5, 5]), ('rows', 'columns'))

In [44]:
gray_named=(img_named[...,:3]*weights_named).sum('channels')


RuntimeError: Error when attempting to broadcast dims ['channels', 'rows', 'columns'] and dims ['channels']: dim 'columns' and dim 'channels' are at the same position from the right but do not match.

In [46]:
gray_plain=gray_named.rename(None)
gray_plain.shape, gray_plain.names

(torch.Size([5, 5]), (None, None))

In [47]:
double_points=torch.ones(10,2,dtype=torch.double)
shorts_points=torch.tensor([[1,2],[3,4]],dtype=torch.short)

In [49]:
shorts_points.dtype

torch.int16

In [51]:
double_points=torch.zeros(10,2).double()
short_points=torch.ones(10,2).short()

In [52]:
double_points=torch.zeros(10,2).to (torch.double)
short_points=torch.ones(10,2).to(dtype=torch.short)

In [53]:
points_64 = torch.rand(5,dtype=torch.double)
points_short = points_64.to(torch.short)
points_64 * points_short 

tensor([0., 0., 0., 0., 0.], dtype=torch.float64)

In [55]:
a=torch.ones(3,2)
a_t=torch.transpose(a,0,1)
a.shape,a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [56]:
a=torch.ones(3,2)
a_t=a.transpose(0,1)
a.shape,a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [58]:
points=torch.tensor([[4.0,1.0], [5.0,3.0], [2.0,1.0]])
points.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [59]:
points_storage=points.storage()
points_storage[0]

4.0

In [60]:
points.storage()[1]

1.0

In [61]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_storage = points.storage()
points_storage[0]=2.0
points

tensor([[2., 1.],
        [5., 3.],
        [2., 1.]])

In [62]:
a=torch.ones(3,2)

In [64]:
a.zero_()
a

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [65]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point=points[1]
second_point.storage_offset()

2

In [66]:
second_point.size()

torch.Size([2])

In [67]:
points.stride()

(2, 1)

In [68]:
second_point.storage_offset()

2

In [69]:
second_point.stride()

(1,)

In [70]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point=points[1]
second_point[0]=10.0
points

tensor([[ 4.,  1.],
        [10.,  3.],
        [ 2.,  1.]])

In [71]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point=points[1].clone()
second_point[0]=10.0
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [72]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [73]:
points_t=points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [75]:
id(points.storage()) == id(points_t.storage())

False

In [76]:
points.stride()

(2, 1)

In [77]:
points_t.stride()

(1, 2)

In [78]:
some_t=torch.ones(3,4,5)
transpose_t=some_t.transpose(0,2)
some_t.shape

torch.Size([3, 4, 5])

In [79]:
transpose_t.shape

torch.Size([5, 4, 3])

In [81]:
some_t.stride()

(20, 5, 1)

In [80]:

transpose_t.stride()

(1, 5, 20)

In [83]:
points.is_contiguous()

True

In [84]:
points_t.is_contiguous()

False

In [85]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [86]:
points_t.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [87]:
points_t.stride()

(1, 2)

In [88]:
points_t_cont=points_t.contiguous()
points_t_cont

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [89]:
points_t_cont.stride()

(3, 1)

In [90]:
points_t_cont.storage()

 4.0
 5.0
 2.0
 1.0
 3.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [94]:
points_gpu = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]], device='cuda')
points_gpu = points.to(device='cuda')

AssertionError: Torch not compiled with CUDA enabled

In [95]:
points_gpu = points.to(device='cuda:0')

AssertionError: Torch not compiled with CUDA enabled

In [96]:
points = 2 * points
points_gpu = 2 * points.to(device='cuda')

AssertionError: Torch not compiled with CUDA enabled

In [98]:
points_gpu = points_gpu + 4
points_gpu = points.cuda()
points_gpu = points.cuda(0)
points_cpu = points_gpu.cpu()

NameError: name 'points_gpu' is not defined

In [99]:
points=torch.ones(3,4)
points_np=points.numpy()
points_np

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [100]:
points=torch.from_numpy(points_np)

In [102]:
torch.save(points, '../data/p1ch3/ourpoints.t')
with open('../data/p1ch3/ourpoints.t','wb') as f:
torch.save(points, f)
points = torch.load('../data/p1ch3/ourpoints.t')
with open('../data/p1ch3/ourpoints.t','rb') as f:
points = torch.load(f)

IndentationError: expected an indented block after 'with' statement on line 2 (2329299253.py, line 3)

In [103]:
conda install h5py

Retrieving notices: ...working... done
Channels:
 - rapidsai
 - nvidia
 - nodefaults
 - conda-forge
 - defaults
Platform: linux-64
Solving environment: done

## Package Plan ##

  environment location: /opt/conda

  added / updated specs:
    - h5py


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-24.9.2               |  py310hff52083_0         895 KB  conda-forge
    h5py-3.12.1                |nompi_py310h60e0fe6_102         1.2 MB  conda-forge
    hdf5-1.14.3                |nompi_hdf9ad27_105         3.7 MB  conda-forge
    libaec-1.1.3               |       h59595ed_0          35 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         5.9 MB

The following NEW packages will be INSTALLED:

  h5py               conda-forge/linux-64::h5py-3.12.1-nompi_py310h60e0fe6_102 
  hdf5               conda-

In [104]:
import h5py
f = h5py.File('../data/p1ch3/ourpoints.hdf5', 'w')
dset = f.create_dataset('coords', data=points.numpy())
f.close()

FileNotFoundError: [Errno 2] Unable to synchronously create file (unable to open file: name = '../data/p1ch3/ourpoints.hdf5', errno = 2, error message = 'No such file or directory', flags = 13, o_flags = 242)

In [ ]:
f = h5py.File('../data/p1ch3/ourpoints.hdf5', 'r')
dset = f['coords']
last_points = dset[-2:]

In [ ]:
last_points = torch.from_numpy(dset[-2:])
f.close()